// src/lib/equipos-data.ts
import type { Equipo } from '@/types';

export const equipos: Equipo[] = [
  {
    nombre: "CLUB ATLETICO ROSARIO CENTRAL",
    nombreCorto: "Rosario Central",
    direccion: "Dirección de Rosario Central",
    estadio: "Estadio de Rosario Central",
    escudoUrl: "/rivales/rosariocentral.png",
  },
  {
    nombre: "CLUB SOCIAL Y DEPORTIVO VILLA NELLY UNIDO",
    nombreCorto: "Villa Nelly Unido",
    direccion: "Dirección de Villa Nelly Unido",
    estadio: "Estadio de Villa Nelly Unido",
    escudoUrl: "/rivales/villanellyunido.png",
  },
  {
    nombre: "CALPINO FUTBOL CLUB",
    nombreCorto: "Calpino",
    direccion: "Dirección de Calpino",
    estadio: "Estadio de Calpino",
    escudoUrl: "/rivales/calpino.png",
  },
  {
    nombre: "CLUB ATLETICO CERRILLOS",
    nombreCorto: "Cerrillos",
    direccion: "Dirección de Cerrillos",
    estadio: "Estadio de Cerrillos",
    escudoUrl: "/rivales/cerrillos.png",
  },
  {
    nombre: "CLUB ATLETICO JUANICO",
    nombreCorto: "Juanico",
    direccion: "Dirección de Juanico",
    estadio: "Estadio de Juanico",
    escudoUrl: "/rivales/juanico.png",
  },
  {
    nombre: "CLUB ATLETICO PROGRESO",
    nombreCorto: "Progreso",
    direccion: "Dirección de Progreso",
    estadio: "Estadio de Progreso",
    escudoUrl: "/rivales/progreso.png",
  },
  {
    nombre: "CLUB DEFENSOR ATLANTA",
    nombreCorto: "Defensor Atlanta",
    direccion: "Dirección de Defensor Atlanta",
    estadio: "Estadio de Defensor Atlanta",
    escudoUrl: "/rivales/defensoratlanta.png",
  },
  {
    nombre: "CLUB DEPORTIVO SAN FRANCISCO",
    nombreCorto: "San Francisco",
    direccion: "Dirección de San Francisco",
    estadio: "Estadio de San Francisco",
    escudoUrl: "/rivales/sanfrancisco.png",
  },
  {
    nombre: "CLUB JUVENTUD MELILLA",
    nombreCorto: "Juventud Melilla",
    direccion: "Dirección de Juventud Melilla",
    estadio: "Estadio de Juventud Melilla",
    escudoUrl: "/rivales/juventudmelilla.png",
  },
  {
    nombre: "CLUB LIBERTAD WASHINGTON",
    nombreCorto: "Libertad Washington",
    direccion: "Dirección de Libertad Washington",
    estadio: "Estadio de Libertad Washington",
    escudoUrl: "/rivales/libertadwashington.png",
  },
  {
    nombre: "DARLING ATLETICO CLUB",
    nombreCorto: "Darling",
    direccion: "Dirección de Darling",
    estadio: "Estadio de Darling",
    escudoUrl: "/rivales/darling.png",
  },
  {
    nombre: "LIVERPOOL CENTRO DEPORTIVO Y SOCIAL",
    nombreCorto: "Liverpool CS",
    direccion: "Dirección de Liverpool CS",
    estadio: "Estadio de Liverpool CS",
    escudoUrl: "/rivales/liverpoolcs.png",
  },
  {
    nombre: "SANTA LUCIA FUTBOL CLUB",
    nombreCorto: "Santa Lucía",
    direccion: "Dirección de Santa Lucía",
    estadio: "Estadio de Santa Lucía",
    escudoUrl: "/rivales/santalucia.png",
  },
  {
    nombre: "WANDERERS ATLETICO CLUB",
    nombreCorto: "Wanderers",
    direccion: "Dirección de Wanderers",
    estadio: "Estadio de Wanderers",
    escudoUrl: "/rivales/wanderers.png",
  },
  {
    nombre: "CLUB AGUAS CORRIENTES",
    nombreCorto: "Aguas Corrientes",
    direccion: "Dirección de Aguas Corrientes",
    estadio: "Estadio de Aguas Corrientes",
    escudoUrl: "/rivales/aguascorrientes.png",
  },
];
